# Generated by Django 4.2 on 2024-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio_comercios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asociacion',
            options={'ordering': ['ciudad__codigo', 'nombre'], 'verbose_name': 'Asociación', 'verbose_name_plural': 'Asociaciones'},
        ),
        migrations.AlterModelOptions(
            name='comercio',
            options={'ordering': ['ciudad__codigo', 'nombre'], 'verbose_name': 'Comercio', 'verbose_name_plural': 'Comercios'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['codigo'], 'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
    ]
